<div class="card" style="background-color: #d0e7ff; color: #000; border: 2px solid #003366;">
    <div class="card-body">
        <h1 class="card-title text-danger" style="color: red; font-size: 2.5rem;">MAKLUMAN!</h1>
        <p>PESANAN KEPADA SEMUA PPD DAN PEMBANTU PENERANGAN (PELAPOR-PELAPOR).</p>
        <p>LAPORAN DI DALAM RIMS BOLEH DILAPOR SEPERTI LAPORAN BIASA.
            <ol>
                <li><strong>PENGGUNAAN HURUF BESAR DAN KECIL</strong> - PASTIKAN PENGGUNAAN HURUF BESAR DAN KECIL ADALAH BETUL PADA KATA NAMA KHAS.</li>
                <li><strong>EJAAN</strong> - SEMAK DAN PASTIKAN EJAAN DITULIS DENGAN BETUL.</li>
                <li><strong>NAMA TEMPAT</strong> - PASTIKAN NAMA TEMPAT DITULIS DENGAN BETUL</li>
                <li><strong>NAMA JAWATAN</strong> - GUNAKAN NAMA JAWATAN YANG STANDARD DAN TEPAT.</li>
                <li><strong>TANDA BACA</strong> - SEMAK PENGGUNAAN NOKTAH (.) DAN PASTIKAN HURUF PERTAMA SELEPAS NOKTAH (.) BERMULA DENGAN HURUF BESAR.</li>
                <li><strong>TULISAN <em>ITALIC</em></strong> - GUNAKAN TULISAN <em>ITALIC</em> UNTUK PERKATAAN YANG BUKAN DALAM BAHASA MELAYU TERUTAMANYA JIKA LAPORAN DIPINDAHKAN ATAU DIEKSTRAK KE DALAM MICROSOFT WORD ATAU CANVA.</li>
                <li><strong>GAYA BAHASA</strong> - SILA GUNAKAN STANDARD PELAPORAN BAHASA MELAYU YANG BETUL DAN ELAKKAN PENGGUNAAN "BAHASA PASAR" (BAHASA LOKAL/BAHASA TEMPATAN) SEPERTI CONTOH "MELENDOT".</li>
                <li>UNTUK <strong>KLUSTER TELEKOMUNIKASI</strong>, ALAMAT PENUH LOKASI, <em>"SCREENSHOT"</em> OKLA SERTA BACAAN MBS WAJID DISERTAKAN.</li>
            </ol>
        </p>
        <p>SEGALA KERJASAMA YANG DIBERIKAN DIDAHULUI DENGAN UCAPAN TERIMA KASIH.</p>
        <P>SEKIAN.</P>
        <p><STRONG>URUS SETIA</STRONG>
            <br>BAHAGIAN GERAK SARAF DAN PENGURUSAN ISU
            <br>JABATAN PENERANGAN MALAYSIA
            <br>DISIARKAN BERMULA 3 JULAI 2025 (KHAMIS)
        </p>
    </div>
</div>